-- 실제 Masters 데이터 반영 (TRI 시약.xlsx 사용자관리/마스터 시트 기준, 2026-08-25)

-- 1) placeholder 제거 (검사자1/2, MODEL-A/B)
delete from masters where kind='inspector' and value in ('검사자1','검사자2');
delete from masters where kind='model' and value in ('MODEL-A','MODEL-B');

-- 2) 실제 검사자 (5명, 사용여부=Y만)
insert into masters (kind, value) values
  ('inspector', 'LEE JUNG YONG'),
  ('inspector', 'VI THI NHUNG'),
  ('inspector', 'DƯƠNG THỊ TRANG'),
  ('inspector', 'VŨ VĂN DƯ'),
  ('inspector', 'Trần văn minh')
on conflict do nothing;

-- 3) 실제 MODEL (84개)
insert into masters (kind, value) values
  ('model', 'H8'),
  ('model', 'B7 SUB'),
  ('model', 'B7 MMW'),
  ('model', 'B7 DUALSIM'),
  ('model', 'B6 SUB'),
  ('model', 'B2 Sub'),
  ('model', 'B0 Sub6'),
  ('model', 'B0 mmW'),
  ('model', 'R0 Sub6'),
  ('model', 'R0 mmW'),
  ('model', 'G0 Sub6'),
  ('model', 'Q5 Main Sub6'),
  ('model', 'Q5 Main mmW'),
  ('model', 'B5 Sub'),
  ('model', 'B5 Main Sub6'),
  ('model', 'B5 Main mmW'),
  ('model', 'B4 Sub'),
  ('model', 'B4 Main Sub6'),
  ('model', 'B4 Main mmW'),
  ('model', 'Q4 Sub'),
  ('model', 'Diamond1 Sub6'),
  ('model', 'Diamond1'),
  ('model', 'Diamond3'),
  ('model', 'Diamond2'),
  ('model', 'PA3 Sub6 SIEL'),
  ('model', 'PA3 Sub6'),
  ('model', 'PA3 mmW'),
  ('model', 'PS mmw'),
  ('model', 'PS Sub6'),
  ('model', 'Q6 Sub'),
  ('model', 'Q6 Main Sub6'),
  ('model', 'Q6 Main'),
  ('model', 'B6 Sub'),
  ('model', 'B6 Main Sub6'),
  ('model', 'B6 Main Dual'),
  ('model', 'B6 Main'),
  ('model', 'B2 Main mmW'),
  ('model', 'B2 Main Sub 6'),
  ('model', 'Q2 Main Sub6'),
  ('model', 'R8'),
  ('model', 'P3'),
  ('model', 'O1'),
  ('model', 'T2'),
  ('model', 'Beyond 1'),
  ('model', 'A82-5G'),
  ('model', 'A51-5G JPN'),
  ('model', 'A51-5G'),
  ('model', 'Canvas 1'),
  ('model', 'Canvas 2'),
  ('model', 'Hubble X1M'),
  ('model', 'Hubble Z3'),
  ('model', 'Hubble X1'),
  ('model', 'Hubble Y2'),
  ('model', 'R3'),
  ('model', 'Star 1'),
  ('model', 'Dream'),
  ('model', 'Davinci 1'),
  ('model', 'Davinci 2'),
  ('model', 'Beyond 2'),
  ('model', 'PA2'),
  ('model', 'PA1'),
  ('model', 'PA1 CNC35 Sub6'),
  ('model', 'E3'),
  ('model', 'E2'),
  ('model', 'E1'),
  ('model', 'R13'),
  ('model', 'Q7 Sub'),
  ('model', 'Q7 Main'),
  ('model', 'B7R Sub'),
  ('model', 'B7R Main Sub6'),
  ('model', 'B7R Main Dual'),
  ('model', 'B7 Sub'),
  ('model', 'B7 Main Sub6'),
  ('model', 'B7 Main Dual'),
  ('model', 'B7 Main mmW'),
  ('model', 'Beyond X'),
  ('model', 'B8 SUB'),
  ('model', 'B8 SUB6'),
  ('model', 'B8 MMW'),
  ('model', 'M3'),
  ('model', 'M2'),
  ('model', 'M1'),
  ('model', 'TN1'),
  ('model', 'TN3')
on conflict do nothing;

-- CA(근무조)는 원본 파일에서 실제 목록을 찾지 못해 기존 CA-A/CA-B placeholder 유지 -- 실제 명칭 있으면 알려주세요

select kind, count(*) from masters group by kind order by kind;
