import 'package:flutter/material.dart';

/// 이중 언어(vi/ko) 문자열. 현장 검사자=베트남어, 관리자=한국어 (스펙 확정).
class S {
  static const List<Locale> supported = [Locale('vi'), Locale('ko')];

  static String t(BuildContext context, String key) =>
      tr(Localizations.localeOf(context).languageCode, key);

  static String tr(String code, String key) =>
      _data[code]?[key] ?? _data['ko']?[key] ?? key;

  static const Map<String, Map<String, String>> _data = {
    'ko': {
      'appTitle': 'TRI 통합 관리',
      'tabProduction': '생산',
      'tabInspect': '검사',
      'tabHistory': '이력',
      'tabDashboard': '대시보드',
      'tabSettings': '설정',
      'productionInput': '생산 투입 등록',
      'qty': '수량',
      'qtyInvalid': '수량을 올바르게 입력하세요',
      'produce': '생산 등록',
      'produced': '생산 등록됨',
      'reworkWaiting': 'Rework 재투입 대기',
      'reworkInputBtn': '재투입',
      'reworkQty': 'Rework 수량',
      'reworkDone': 'Rework 재투입 등록됨',
      'reworkQtyWarn': 'Rework 수량이 생산 수량을 초과합니다 (저장됨)',
      'selectLot': '미검사 LOT 선택',
      'selectLotFirst': '검사할 생산 LOT을 먼저 선택하세요',
      'refreshLots': '미검사 목록 새로고침',
      'prodTotal': '생산 건수',
      'prodQty': '생산 수량',
      'inspectRate': '검사율',
      'uninspectedCnt': '미검사',
      'reworkRate': 'Rework율',
      'prodTrend': '기간별 추이 (일별 생산·NG)',
      'prodStatsTitle': '생산 지표',
      'date': '날짜',
      'ca': '근무조(CA)',
      'inspector': '검사자',
      'lot': 'LOT 번호',
      'lotAuto': 'LOT 번호는 저장 시 자동 부여 (업무일 08:00 기준, 예: 260706001)',
      'bar': 'Bar 번호(대차)',
      'model': 'Model',
      'result': '판정',
      'verdict': '종합판정',
      'photo': '사진',
      'addPhoto': '사진 촬영',
      'photoRequired': '사진을 최소 1장 촬영해야 저장할 수 있습니다',
      'photoPerRackRequired': 'Rack 1~5 각각 사진 1장(총 5장)을 촬영해야 저장할 수 있습니다',
      'fieldRequired': '필수 입력 항목입니다',
      'save': '저장',
      'savedOk': '저장됨 — 종합판정 OK',
      'savedNg': '저장됨 — 종합판정 NG (Rework 대상 등록)',
      'search': '조회',
      'ngOnly': 'NG만',
      'dateFrom': '시작일',
      'dateTo': '종료일',
      'noData': '데이터 없음',
      'rework': 'Rework',
      'voided': '무효',
      'voidAction': '기록 무효화',
      'voidConfirm': '이 기록을 무효화합니까? (삭제되지 않고 무효 표시됨. 정정은 재입력으로)',
      'cancel': '취소',
      'confirm': '확인',
      'total': '전체 건수',
      'ngCount': 'NG 건수',
      'ngRate': 'NG율',
      'pendingPhotos': '전송 대기 사진',
      'byModel': 'Model별 현황',
      'monitoring': '품질 모니터링',
      'myToday': '금일 검사',
      'myNg': '금일 NG',
      'language': '언어',
      'appearance': '화면 테마',
      'themeSystem': '시스템 설정 따름',
      'themeLight': '라이트',
      'themeDark': '다크',
      'syncStatus': '동기화 상태',
      'pendingRecords': '전송 대기 기록',
      'syncNow': '지금 동기화',
      'syncWarning': '전송 실패가 반복되고 있습니다. 네트워크를 확인하세요.',
      'apiUrl': '서버 URL (Apps Script)',
      'appToken': '앱 토큰',
      'settingsSaved': '설정이 저장되었습니다',
      'networkError': '네트워크 오류 — 연결 후 다시 시도하세요',
      'detail': '상세',
      'photos': '사진',
      'photoPending': '사진 전송 대기 중',
      'openLink': '열기',
      'refreshMasters': '목록 새로고침 (검사자/Model)',
      'time': '시간',
      'period': '기간',
      'loading': '불러오는 중...',
      'selectInspector': '설정에서 검사자를 먼저 선택하세요',
      'notSet': '미설정',
    },
    'vi': {
      'appTitle': 'Quản lý tích hợp TRI',
      'tabProduction': 'Sản xuất',
      'tabInspect': 'Kiểm tra',
      'tabHistory': 'Lịch sử',
      'tabDashboard': 'Thống kê',
      'tabSettings': 'Cài đặt',
      'productionInput': 'Đăng ký đầu vào sản xuất',
      'qty': 'Số lượng',
      'qtyInvalid': 'Vui lòng nhập số lượng hợp lệ',
      'produce': 'Đăng ký sản xuất',
      'produced': 'Đã đăng ký sản xuất',
      'reworkWaiting': 'Chờ tái đầu vào Rework',
      'reworkInputBtn': 'Tái đầu vào',
      'reworkQty': 'Số lượng Rework',
      'reworkDone': 'Đã đăng ký tái đầu vào Rework',
      'reworkQtyWarn': 'Số lượng Rework vượt số lượng sản xuất (đã lưu)',
      'selectLot': 'Chọn LOT chưa kiểm tra',
      'selectLotFirst': 'Vui lòng chọn LOT sản xuất để kiểm tra',
      'refreshLots': 'Làm mới danh sách chưa kiểm tra',
      'prodTotal': 'Số lần sản xuất',
      'prodQty': 'SL sản xuất',
      'inspectRate': 'Tỷ lệ kiểm tra',
      'uninspectedCnt': 'Chưa KT',
      'reworkRate': 'Tỷ lệ Rework',
      'prodTrend': 'Xu hướng theo ngày (SX·NG)',
      'prodStatsTitle': 'Chỉ số sản xuất',
      'date': 'Ngày',
      'ca': 'CA',
      'inspector': 'Người kiểm tra',
      'lot': 'Số LOT',
      'lotAuto': 'Số LOT được cấp tự động khi lưu (theo ngày làm việc bắt đầu 08:00, VD: 260706001)',
      'bar': 'Số Bar',
      'model': 'Model',
      'result': 'Kết quả',
      'verdict': 'Phán định tổng hợp',
      'photo': 'Ảnh',
      'addPhoto': 'Chụp ảnh',
      'photoRequired': 'Phải chụp ít nhất 1 ảnh mới lưu được',
      'photoPerRackRequired': 'Phải chụp 1 ảnh cho mỗi Rack 1~5 (tổng 5 ảnh) mới lưu được',
      'fieldRequired': 'Mục bắt buộc',
      'save': 'Lưu',
      'savedOk': 'Đã lưu — Kết quả OK',
      'savedNg': 'Đã lưu — Kết quả NG (Đăng ký Rework)',
      'search': 'Tra cứu',
      'ngOnly': 'Chỉ NG',
      'dateFrom': 'Từ ngày',
      'dateTo': 'Đến ngày',
      'noData': 'Không có dữ liệu',
      'rework': 'Rework',
      'voided': 'Đã hủy',
      'voidAction': 'Hủy bản ghi',
      'voidConfirm': 'Hủy bản ghi này? (Không xóa, chỉ đánh dấu hủy. Sửa bằng cách nhập lại)',
      'cancel': 'Hủy',
      'confirm': 'Xác nhận',
      'total': 'Tổng số',
      'ngCount': 'Số NG',
      'ngRate': 'Tỷ lệ NG',
      'pendingPhotos': 'Ảnh chờ gửi',
      'byModel': 'Theo Model',
      'monitoring': 'Giám sát chất lượng',
      'myToday': 'Kiểm tra hôm nay',
      'myNg': 'NG hôm nay',
      'language': 'Ngôn ngữ',
      'appearance': 'Giao diện',
      'themeSystem': 'Theo hệ thống',
      'themeLight': 'Sáng',
      'themeDark': 'Tối',
      'syncStatus': 'Trạng thái đồng bộ',
      'pendingRecords': 'Bản ghi chờ gửi',
      'syncNow': 'Đồng bộ ngay',
      'syncWarning': 'Gửi thất bại nhiều lần. Vui lòng kiểm tra mạng.',
      'apiUrl': 'URL máy chủ (Apps Script)',
      'appToken': 'Mã token ứng dụng',
      'settingsSaved': 'Đã lưu cài đặt',
      'networkError': 'Lỗi mạng — thử lại sau khi kết nối',
      'detail': 'Chi tiết',
      'photos': 'Ảnh',
      'photoPending': 'Ảnh đang chờ gửi',
      'openLink': 'Mở',
      'refreshMasters': 'Làm mới danh sách (Người kiểm tra/Model)',
      'time': 'Thời gian',
      'period': 'Khoảng thời gian',
      'loading': 'Đang tải...',
      'selectInspector': 'Vui lòng chọn người kiểm tra trong Cài đặt',
      'notSet': 'Chưa cài đặt',
    },
  };
}
